#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumSwaps function below.
def minimumSwaps(arr):
    c=0
    n=len(arr)
    for i in range(n):
        while arr[i]-1!=i:
            e=arr[i]
            arr[e-1],arr[i]=arr[i],arr[e-1]
            c+=1    
    return c

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    res = minimumSwaps(arr)

    fptr.write(str(res) + '\n')

    fptr.close()
